FROM maven:3.9-eclipse-temurin-21

# Устанавливаем postgresql-client для проверки БД
RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
COPY wait-for-db.sh /wait-for-db.sh
RUN chmod +x /wait-for-db.sh

# Упрощенная команда запуска
CMD ["/wait-for-db.sh", "test_db", "5432", "mvn", "test"]