FROM maven:3.9-eclipse-temurin-21

# Установка postgresql-client и проверка формата скрипта
RUN apt-get update && \
    apt-get install -y postgresql-client dos2unix && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src

# Копирование и преобразование формата строк
COPY scripts/wait-for-db.sh /usr/local/bin/wait-for-db
RUN dos2unix /usr/local/bin/wait-for-db && \
    chmod +x /usr/local/bin/wait-for-db

CMD ["sh", "-c", "wait-for-db test_db 5432 mvn test"]