services:
  yandex-practicum-blog:
    profiles: ["prod"]
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    depends_on:
      blog-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://blog-db:5432/blog_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_DRIVER=org.postgresql.Driver
      - DB_NAME=blog_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - DB_HOST=blog-db
      - DB_PORT=5432

  blog-db:
    profiles: ["prod"]
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    profiles: ["test"]
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - "9091:8080"
    depends_on:
      test_db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://test_db:5432/test_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_DRIVER=org.postgresql.Driver
      - DB_NAME=test_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - DB_HOST=test_db
      - DB_PORT=5432
    healthcheck:
      test: [ "CMD", "sh", "-c", "[ -f /app/target/surefire-reports/TEST-*.xml ]" ]
      interval: 5s
      timeout: 5s
      retries: 10

  test_db:
    profiles: ["test"]
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  test_postgres_data: