-- INSERT INTO tags (tag_uuid, title) VALUES
-- (gen_random_uuid(), 'Программирование'),
-- (gen_random_uuid(), 'Python'),
-- (gen_random_uuid(), 'JavaScript'),
-- (gen_random_uuid(), 'C++'),
-- (gen_random_uuid(), 'Машинное обучение');
--
-- INSERT INTO posts (post_uuid, title, image_url, text_content, likes) VALUES
-- (gen_random_uuid(), 'Как начать программировать', 'https://images.unsplash.com/photo-1627398242454-45a1465c2479', 'Программирование — это увлекательный процесс, который требует практики...', 10),
-- (gen_random_uuid(), 'Лучшие книги по Python', 'https://images.unsplash.com/photo-1580121441575-41bcb5c6b47c', 'Python — один из самых популярных языков программирования. Вот список книг...', 15),
-- (gen_random_uuid(), 'Основы JavaScript', 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a', 'JavaScript — это язык программирования для создания интерактивных веб-страниц...', 12),
-- (gen_random_uuid(), 'Советы по изучению C++', 'https://sun9-57.userapi.com/impf/c854524/v854524947/11f72b/9MfohpKI32Q.jpg?size=1280x855&quality=96&sign=c77794160ca2df24bf95b3c43fb05a91&type=album', 'C++ — мощный язык программирования, который используется в разработке игр...', 8),
-- (gen_random_uuid(), 'Введение в машинное обучение', 'https://avatars.mds.yandex.net/i?id=89e12fa7b44fabd837150e03e412e95a_l-5151239-images-thumbs&n=13', 'Машинное обучение — это область искусственного интеллекта, которая...', 25);
--
-- INSERT INTO post_tags (pt_uuid, post_uuid, tag_uuid) VALUES
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Как начать программировать'), (SELECT tag_uuid FROM tags WHERE title = 'Программирование')),
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Лучшие книги по Python'), (SELECT tag_uuid FROM tags WHERE title = 'Программирование')),
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Лучшие книги по Python'), (SELECT tag_uuid FROM tags WHERE title = 'Python')),
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Основы JavaScript'), (SELECT tag_uuid FROM tags WHERE title = 'JavaScript')),
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Советы по изучению C++'), (SELECT tag_uuid FROM tags WHERE title = 'C++')),
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Введение в машинное обучение'), (SELECT tag_uuid FROM tags WHERE title = 'Машинное обучение'));
--
-- INSERT INTO comments (comment_uuid, post_uuid, text_content) VALUES
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Как начать программировать'), 'Отличная статья, спасибо!'),
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Лучшие книги по Python'), 'Какие книги вы бы порекомендовали?'),
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Основы JavaScript'), 'JavaScript — это круто!'),
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Советы по изучению C++'), 'C++ сложный, но интересный!'),
-- (gen_random_uuid(), (SELECT post_uuid FROM posts WHERE title = 'Введение в машинное обучение'), 'Машинное обучение — это будущее!');